siliconbiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("", include("distributors.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path


from . import views
from .auth import (
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)
from . import auth

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from users.auth import adminlogin


urlpatterns = [

    path("dashboard/", views.dashboard, name="dashboard"),


    path('login', adminlogin, name='login'),

    # path("login", LoginView.as_view(template_name='auth/login.html'), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    # path("login_success", LoginSuccess.as_view(), name="login_success_employee"),

    # path("logout", Logout.as_view(), name="logout_company"),
    path("password_reset", CustomPasswordResetView.as_view(),
         name="password_reset"),
    path(
        "reset-password-sent/",
        CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset-password-complete/",
        CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # !


    path(
        'Password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='auth/password_change_form.html',
            success_url=reverse_lazy('password_change_done')
        ),
        name='password_change'
    ),


    path("password_change_done/", auth.change_done, name="password_change_done"),



]

distributors/models.py
from django.db import models
from django.conf import settings
from datetime import datetime

from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()


class Vehicle(models.Model):
    vehicle_name = models.CharField(max_length=100)
    capacity = models.CharField(max_length=50, null=True, blank=True)
    company = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.vehicle_name


class Driver(models.Model):
    name = models.CharField(max_length=100)
    national_id = models.PositiveIntegerField('ID', unique=True)
    users = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    mobile_number = models.PositiveIntegerField(
        'Mobile Number', unique=True, null=True, blank=True)
    email = models.EmailField(verbose_name="Email",
                              max_length=100, unique=True)

    def __str__(self):
        return self.name


class Town(models.Model):
    name = models.CharField(max_length=100)
    created = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'town'
        verbose_name = 'Town'
        verbose_name_plural = 'Towns'


class Route(models.Model):
    route_name = models.CharField(max_length=100, null=True, blank=True)
    cities = models.CharField(max_length=100, null=True, blank=True)
    created = models.BooleanField(default=False)

    def __str__(self):
        return self.route_name


class CustomerRelation(models.Model):
    customer_name = models.CharField(max_length=100)
    customer_address = models.TextField(null=True, blank=True)
    town = models.ForeignKey(
        'Town', on_delete=models.DO_NOTHING, null=True, blank=True)
    Customer_pin = models.CharField(
        max_length=100, unique=True, null=True, blank=True)
    contact_person_number = models.PositiveIntegerField(null=True, blank=True)
    contact_person_name = models.CharField(
        max_length=100, null=True, blank=True)
    account = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.customer_name


class Valuer(models.Model):
    valuer_name = models.CharField(max_length=100)
    valuer_email = models.EmailField(null=True, blank=True)
    valuer_number = models.PositiveIntegerField(null=True, blank=True)
    valuer_address = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.valuer_name


class ConsignmentNote(models.Model):
    sender_name = models.ForeignKey(
        'CustomerRelation', on_delete=models.DO_NOTHING, related_name='sender_name')
    consignee = models.ForeignKey(
        'CustomerRelation', on_delete=models.DO_NOTHING, related_name='consignee')
    reference_no = models.CharField(max_length=100, null=True, blank=True)
    route = models.ForeignKey(
        'Route', on_delete=models.CASCADE, null=True, blank=True)
    town = models.ForeignKey(
        'Town', on_delete=models.DO_NOTHING, null=True, blank=True)
    document = models.ForeignKey(
        'distributors.Document', on_delete=models.DO_NOTHING)
    description = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField()
    bundle = models.PositiveIntegerField()
    rate = models.PositiveIntegerField()
    per = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    tax = models.CharField(max_length=100, null=True, blank=True)
    inclusive = models.CharField(max_length=100, null=True, blank=True)
    tracking_no = models.PositiveIntegerField(default=0)
    is_delivered = models.BooleanField(default=False)
    valuer = models.ForeignKey(
        'Valuer',  on_delete=models.DO_NOTHING, null=True, blank=True)
    date_created = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.pk}'

    class Meta:
        db_table = 'consignment_note'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # check if date_created is provided and if not, set it to today
        if self.date_created:
            self.date_created = self.date_created
        else:
            self.date_created = datetime.date.today()

templates/create_customer.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">Customers</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <form action="{{ request.path }}" method="post">
                  {{ form.errors }}
                  {% csrf_token %}
                  {% include 'form_fields.html' %}
                  <button type="submit" class="btn btn-primary">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/create_valuer.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">Valuers</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <form action="{{ request.path }}" method="post">
                  {{ form.errors }}
                  {% csrf_token %}
                  {% include 'form_fields.html' %}
                  <button type="submit" class="btn btn-primary">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/driver.html
{% extends 'base.html' %}
{% block content %}
  <div class="row vh-100">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">Driver</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                        <form action="{{ request.path }}" method="post">
                  {{ form.errors }}
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="id_name">Driver  Name</label>
                    {% comment %} <input type="text" class="form-control rounded" name="vehicle_name" id="id_name"> {% endcomment %}
                    {{form.name}}
                  </div>


                        <div class="form-group">
                    <label for="id_name">National ID</label>
                    {% comment %} <input type="text" class="form-control rounded" name="capacity" id="id_name"> {% endcomment %}
      {{form.national_id}}                  
                </div>



                      <div class="form-group">
                    <label for="id_name">Mobile Number</label>
                    {% comment %} <input type="text" class="form-control rounded" name="company" id="id_name"> {% endcomment %}
   {{form.mobile_number}} 

                  </div>



                      <div class="form-group">
                    <label for="id_name">Email</label>
                    {% comment %} <input type="text" class="form-control rounded" name="company" id="id_name"> {% endcomment %}
   {{form.email}} 

                  </div>

                  
                  <button type="submit" class="btn btn-primary">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/form_fields.html
{% for field in form %}
  {% include 'form_field.html' with field=field %}
{% endfor %}

templates/login.html
 {% extends 'baselogin.html' %}

{% block content %}

{% comment %} <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form> {% endcomment %}



    <body id="main-container" class="default">
        <!-- START: Main Content-->
        <div class="container">
            <div class="row vh-100 justify-content-between align-items-center">
                <div class="col-12">
                     <form action="#" class="row row-eq-height lockscreen  mt-5 mb-5"  method="post">  
                        {{form.errors}}
                           {% csrf_token %}
                        <div class="lock-image col-12 col-sm-5"></div>
                        <div class="login-form col-12 col-sm-7"> 
                        <h2>Login</h2>

                    <div class="form-group mb-3">
              <label for="id_name">Email</label>
              <input class="form-control" type="email" id="email" name="email" required placeholder="Enter your Email">
            </div>



            <div class="form-group mb-3">
              <label for="id_password">Password</label>
              <input class="form-control" type="password" required id="id_password" name="password"
                     placeholder="Enter your password">
            </div>


            <div class="form-group mb-0">
              <button class="btn btn-primary" type="submit"> Log In</button>
            </div>
                             </div>
                    </form> 
                </div>

            </div>
        </div>








<a href="{% url 'dashboard' %}">Back to dashboard</a>
<a href="{% url 'password_reset' %}">Reset password</a>
{% endblock %} 

templates/note-download.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consignment Note</title>
    <style>
        .title{
            margin-bottom: 4px;
            text-align: center;
        }
        p{
            font-size: 8px;
        }
        h6{
            font-size: 8px;
        }

        th, td{
            font-size: 8px;
        }
        .sub-title{
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="row min-vh-75">
        <div class="card w-100 mx-4 p-4 ">
            <div class="card-title">
                <h4 class="title">Consignment Note</h4>
                <br/>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <div>
                        <p class="sub-title">KAMONGO WASTE PAPER (KENYA) LTD</p>
                        <p>P.O. BOX 673313-00200, NAIROBI, KENYA</p>
                        <p>Tel: 020 2620498 / 8045369</p>
                        <p>Cel: 0720 555240 / 0733 555559</p>
                        <p>Email: info@kamongo.co.ke</p>
                    </div>
                    <div>
                        <p>PIN NO: P051677579F</p>
                    </div>
                    <!-- <p>Consignment Note No: {{notes.pk}}</p>
                    <p>{{notes.date_created}}</p> -->
                </div>
                <br/>
                <div class="">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex flex-column" style="flex-grow: 4;">
                            <div> 
                                <p>Sender Name</p>
                                <p>Address</p>
                            </div>
                            <div class="ml-4">
                                <p>{{notes.sender_name}}</p>
                                <p>{{notes.sender_name.customer_address}}</p>
                            </div>
                        </div>
                        <div class="d-flex flex-column justify-content-right" style="flex-grow: 2;">
                            <div>
                                <p>Date</p>
                                <p>Consignee</p>
                                <p>Address</p>
                            </div>
                            <div class="ml-4">
                                <p>{{notes.date_created}}</p>
                                <p>{{notes.consignee}}</p>
                                <p>{{notes.consignee.customer_address}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br/>
                <div class="table-responsive">
                    <table
                    class="table table-hover border table-stripped table-vcenter table-striped"
                    cellspacing="0"
                    >
                        <thead class="table bg-primary text-white">
                            <tr>
                                <td>Weight</td>
                                <td>Quantity</td>
                                <td>@</td>
                                <td>Ksh</td>
                                <!-- <td>Exclusive</td>
                                <td>Tax</td>
                                <td>Inclusive</td> -->
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><div class="d-flex flex-column">
                                        <p>{% if notes.per == 1 %} Bundle {% else %} Kgs {% endif %}</p>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-flex flex-column">
                                        <p>{{notes.quantity}}</p>
                                    </div>
                                </td>
                                <td><div class="d-flex flex-column"><p>{{notes.rate}}</p></div></td>
                                <td><p>{{notes.inclusive}} </p></td>
                                <!-- <td><p>{{notes.tax}} </p></td>
                                <td><p>{{notes.inclusive}} </p></td> -->
                            </tr>
                            <tr>
                                <td>
                                    <div>
                                    </div>
                                </td>
                                <td  colspan="2">
                                    <div class="d-flex flex-column">
                                        <p>Total</p>
                                    </div>
                                </td>
                                <td>{{notes.inclusive}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div> 
                <div class="d-flex flex-row">
                    <div>
                        <h4><p>IMPORTANT</p></h4><p>All gooods stored and carried at owners's risk and the company will not be liable in any way whatsoever for negligence of the company or its agents. Without prejudice to the generality of the foregoing the company will not be responsible for any loss, damage, delay, or detention of any goods due to any collision, overturning, robbery, theft civil commotion riot or disturbances, war or inherent vice or defict in goods carried, defective packaging of faulty, wrong or insufficient address of the consignee. The company shall have a general as well as particular lien on all goods for unpaid accounts</p>
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <h6 style="width: 60%;">FRAGILE GOODS RECEIVED CONTENTS NOT CHECKED COMPANY NOT LIABLE FOR BREAKAGE / DAMAGE ON TRANSIT</h6>
                    <h6 style="flex-grow: 4;" class="d-flex justify-content-right"">Vehicle No. ....................................</h6>
                </div>
                <div>
                    <p>_____________________________________________</p>
                    <p class="sub-title">Please Sign with rubberstamp</p>
                </div>
            </div>
        </div>
      </div>
</body>
</html>

templates/note_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex justify-content-between">
        <a href="{% url 'note-list' %}" type="button" class="btn btn-primary ml-2 mb-2">
            <i class="fa fa-arrow-left mr-2"></i>
            Back
        </a>
        <a target="_blank" href="{% url 'note-print' notes.pk %}" type="button" class="btn btn-secondary mb-2 mr-2">
            <i class="fa fa-print mr-2"></i>
            Print
        </a>
    </div>
    <div class="row min-vh-75">
    <div class="card w-100 mx-4 p-4 ">
        <div class="card-title">
            <h4>Inventory Voucher</h4>
        </div>
        <div class="card-body">
            <div class="d-flex justify-content-between">
                < >Consignment Note No: {{notes.reference_no}}</>
                <p>{{notes.date_created}}</p>
            </div>
            <div class="d-flex justify-content-left">
                <div class="d-flex justify-content-between">
                    <div>
                        <p>Sender Name</p>
                        <p>Consignee</p>
                        <p>Route</p>
                        <p>Type</p>
                    </div>
                    <div class="ml-4">
                        <p>{{notes.sender_name}}</p>
                        <p>{{notes.consignee}}</p>
                        <p>{{notes.route}}</p>
                        <p>{{notes.document}}</p>
                    </div>
                </div>
            </div>
            <div class="table-responsive my-4">
                <table
                class="table table-hover border table-stripped table-vcenter table-striped"
                cellspacing="0"
                >
                    <thead class="table bg-primary text-white">
                        <tr>
                            <td>Name of Item</td>
                            <td>Quantity</td>
                            <td>Rate</td>
                            <td>Per</td>
                            <td>Amount</td>
                            <td>Tax</td>
                            <td>Inclusive</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><div class="d-flex flex-column">
                                    <p>Transportation</p>
                                    <p class="text-muted">{{notes.description}}</p>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex flex-column">
                                    <p>{{notes.quantity}} Kgs</p>
                                    <p class="text-muted" >({{notes.bundle}} bundle)</p>
                                </div>
                            </td>
                            <td>{{notes.rate}}</td>
                            <td>{{notes.per}}</td>
                            <td>{{notes.amount}}</td>
                            <td>{{notes.tax}}</td>
                            <td>{{notes.inclusive}}</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>{{notes.quantity}} {% if notes.per == '1' %} Kgs {% else %} Bundle {% endif %}</td>
                            <td></td>
                            <td></td>
                            <td>{{notes.inclusive}}</td>
                        </tr>
                    </tbody>
                </table>
            </div> 
            <div class="d-flex flex-column my-4">
                <p>Valuer: {{notes.valuer}}</p>
                <p>Narations is delivered: {% if notes.is_delivered %} Yes {% else %} No {% endif %} </p>
            </div>
            
        </div>
    </div>
  </div>

{% endblock content %}

templates/town.html
{% extends 'base.html' %}

{% block content %}
  <div class="row vh-100">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">New Town</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <form action="{{ request.path }}" method="post">
                  {{ form.errors }}
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="id_name">Name</label>
                    <input type="text" class="form-control rounded" name="name" id="id_name">
                  </div>
                  <button type="submit" class="btn btn-primary">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/valuers_list.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
  <div class="d-flex justify-content-end align-items-center mb-3">

    <div class="header-action">
      <a href="{% url 'valuer-create' %}" class="btn btn-outline-primary"><i
        class="fa fa-plus mr-2"></i>New Valuer
      </a>
    </div>
  </div>
  <div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h4 class="card-title">Valuers</h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Address</th>
            <th scope="col">Action</th>
          </tr>
          </thead>
          <tbody>
          {% for valuer in valuers %}
            <tr>
              <th>{{ valuer.pk }}</th>
              <td>{{ valuer.valuer_name }}</td>
              <td>{{ valuer.valuer_email }}</td>
              <td>{{ valuer.valuer_number }}</td>
              <td>{{ valuer.valuer_address }}</td>
              <td>

                <a href="{% url 'valuer-update' valuer.pk %}" class="mr-3"><i class="fa fa-edit text-success"></i></a>
                <a href="{% url 'valuer-delete' valuer.pk %}" class=""><i class="fa fa-trash text-danger"></i></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% if valuers.has_other_pages %}
        <div class="mt-4">
          <ul class="pagination">
            {% if valuers.has_previous %}
              <li class="page-item">
                <a class="page-link" href="{% url 'valuers' %}?page={{ valuers.previous_page_number }}">
                  <i class="fa fa-angle-left"></i>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">
                  <i class="fa fa-angle-left"></i>
                </a>
              </li>
            {% endif %}

            {% if valuers.number|add:'-4' > 1 %}
              <li class="page-item">
                <a class="page-link" href="{% url 'valuers' %}?page={{ valuers.page|add:"-5" }}">
                  &hellip;
                </a>
              </li>
            {% endif %}

            {% for page in valuers.paginator.page_range %}
              {% if page == valuers.number %}
                <li class="page-item active">
                  <a class="page-link" href="{% url 'valuers' %}?page={{ page }}">{{ page }}</a>
                </li>
              {% elif page > valuers.number|add:'-5' and page < valuers.number|add:'5' %}
                <li class="page-item">
                  <a class="page-link" href="{% url 'valuers' %}?page={{ page }}">{{ page }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if valuers.paginator.num_pages > valuers.number|add:'4' %}
                <li class="page-item"><a class="page-link" href="?page={{ valuers.number|add:'5' }}">&hellip;</a></li>
            {% endif %}

            {% if valuers.has_next %}
              <li class="page-item">
                <a class="page-link" href="{% url 'valuers' %}?page={{ valuers.next_page_number }}">
                  <i class="fa fa-angle-right"></i>
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">
                  <i class="fa fa-angle-right"></i>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      {% endif %}

    </div>
  </div>
{% endblock %}

templates/vehicle.html
{% extends 'base.html' %}

{% block content %}
  <div class="row vh-100">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">Vehicle</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <form action="{{ request.path }}" method="post">
                  {{ form.errors }}
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="id_name">Vehicle name</label>
                    {% comment %} <input type="text" class="form-control rounded" name="vehicle_name" id="id_name"> {% endcomment %}
                    {{form.vehicle_name}}
                  </div>


                        <div class="form-group">
                    <label for="id_name">Vehicle Capacity</label>
                    {% comment %} <input type="text" class="form-control rounded" name="capacity" id="id_name"> {% endcomment %}
      {{form.capacity}}                  
                </div>



                      <div class="form-group">
                    <label for="id_name">Vehicle Company</label>
                    <input type="text" class="form-control rounded" name="company" id="id_name">
                  </div>

                  
                  <button type="submit" class="btn btn-primary">Save</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/vehicle_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="d-flex justify-content-end align-items-center mb-3">

    <div class="header-action">
      <a href="{% url 'vehicle' %}" class="btn btn-outline-primary"><i
        class="fa fa-plus mr-2"></i>New Vehicle
      </a>
    </div>
  </div>
  <div class="row vh-100">
    <div class="col-12 mt-4">
      <div class="card">
        <div class="card-header">
          <h6 class="card-title">Vehicle list</h6>
        </div>
        <div class="card-content">
          <div class="card-body">
            <div class="row">
              <div class="col-12">
                <table class="table table-striped table-vcenter table-hover mb-0">
                  <thead class="thead-dark">
                  <tr>
                    <th>#</th>
                    <th>Vehicle Name</th>
                    <th>Capacity</th>
                    <th>Company</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for vehicle in vehicles %}
                    <tr>
                      <th>{{ forloop.counter }}</th>
                      <td>{{ vehicle.vehicle_name }}</td>
                      <td>{{ vehicle.capacity }}</td>
                      <td>{{ vehicle.company }}</td>
{#                      <td>{{ vehicle. }}</td>#}
                      <td>
                        <a href="{% url 'vehicle-detail' vehicle.pk %}" class="mr-3"><i
                          class="fa fa-edit text-success"></i></a>
                        <a href="{% url 'vehicle-delete' vehicle.pk %}" class=""><i
                          class="fa fa-trash text-danger"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}